### ISSUE TITLE
Some questions regarding the minimal sample.

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fable2-samples#1]
1. I noticed the `fsproj` contains `<PackageReference />`. I Seem to recall that Fable 1.X had a hard dependencies on paket because it needed the lock file to figure out what to compile. So this dependency is gone in Fable2?

2. Each time the app rebuilds, it restores the packages of the fsproj. This is handy but only seems necessary if the packages actually changed. Any plans to watch the entry point for changes?

3. Which Babel presets are used to compile to?

4. Will Babel 7 be used when stable?

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the questions @nojaf. I try to respond below:

1. Yes, in Fable 2 we're resolving the dependency order by ourselves and so far it's working fine so Paket is not strictly necessary. We'll likely still use it in most of the examples, but I wanted to show that it's not needed in the minimal configuration. I'll write that when updating the docs :+1:
2. Sorry, I didn't notice that. Apparently it was because I set `mode: "none"` in Webpack configuration. I've changed it to `development` and not it's only restoring the packages if you edit the .fsproj file. Fable 2 is running `dotnet restore` by default in case users install it as a global tool (or in a separate project) and forget to restore nuget dependencies before running `dotnet fable`.
3. In the minimal sample no Babel preset is used, as Fable 2 is mostly outputting ES5 code and I wanted to show a webpack.config.js file as slim as possible. However, in most of the other samples we will be using the `env` preset which is what Babel recommends now. This usually outputs ES5 unless you edit the browser list to only support very modern browsers (although in those cases I've seen issues with uglify minification as it only supports ES5). More info [here](https://github.com/fable-compiler/webpack-config-template/blob/874a476179fa09cd2546be35d392b4a5e317c9cf/webpack.config.js#L17).
4. I was planning to update to Babel 7 like we've updated to Webpack 4. However, I had some issues with our custom Babel plugins and couldn't find any documentation or Typescript declaration files for Babel 7. So we will likely keep using Babel 6 until the new version is stable and well documented.

Hope this helps!

**Comment by nojaf** [comment]
Thanks Alfonso! Maybe once last question regarding **3**, you mention that Fable 2 outputs ES5 code.
Does this mean that something changed internally? 

Is Fable still going from `F# source -> FSC AST -> Fable AST -> Babel AST -> JavaScript`?

**Comment by alfonsogarciacaro** [comment]
Well, actually I was wrong. Fable 2 doesn't use ES2015 classes but still uses let and const so you'll need a Babel preset to run on old browsers. In any cases, the flow is still the same. Fable only produces a JSON AST and Babel generates the actual JS code and source maps, even if you don't use any plugin/preset (Fable has a couple of custom plug-ins to transform Emit macros, for example).
