### ISSUE TITLE
Samples don't build on current .NET Core SDK

### ISSUE THREAD

**Issue by rolandcrosby** [fable-compiler/fable2-samples#25]
I'm trying to follow the instructions in [the quick start](https://fable.io) and [the Fable docs](https://fable.io/docs/2-steps/choose-a-template.html), and I'm getting an error message saying that the samples require Microsoft.NETCore.App 2.1.0.

Is there a plan to update the samples so they build on .NET Core 3.1? If not, could the Fable docs be updated to indicate the correct requirements?

**Comment by MangelMaxime** [comment]
Hello,

I think it's because the samples are using an old version of `fable-compiler` ([version 2.3.19](https://github.com/fable-compiler/fable2-samples/blob/master/browser/package.json)) while  I think running Fable against dotnet core 3 is supported since [version 2.4.0](https://github.com/fable-compiler/Fable/blob/master/src/fable-compiler/RELEASE_NOTES.md#240) only.

We should upgrade all the npm and NuGet dependencies in order to benefit from the latest features etc.
